name: ea_proyecto_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^20.3.57

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.1
  provider: ^6.0.2
  image_picker: ^1.0.4
  cloudinary: ^1.2.0
  dotted_border: ^2.0.0+2
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_rating_bar: ^4.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_marker_popup: ^6.1.2
  jwt_decoder: ^2.0.1
  socket_io_client: ^2.0.3+1
  emoji_picker_flutter: ^1.6.3
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  timetable_view: ^0.3.0
  table_calendar: ^3.0.1
  flutter_pw_validator: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/

# fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700