// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCgXHQwabhSmnLruArPUm5o4_zOqssyM',
    appId: '1:667305405602:web:23b171ad72b078c9c47bfb',
    messagingSenderId: '667305405602',
    projectId: 'eetaceaapp',
    authDomain: 'eetaceaapp.firebaseapp.com',
    storageBucket: 'eetaceaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAny2oXAchJYtBw2_fEqse_ut_Ojf4n5pA',
    appId: '1:667305405602:android:587ebf5d6e4d3077c47bfb',
    messagingSenderId: '667305405602',
    projectId: 'eetaceaapp',
    storageBucket: 'eetaceaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8jMEEzbXWsZ8WxofGxoo3VGoDiTApxTI',
    appId: '1:667305405602:ios:0c5695188ca4e85bc47bfb',
    messagingSenderId: '667305405602',
    projectId: 'eetaceaapp',
    storageBucket: 'eetaceaapp.appspot.com',
    iosClientId: '667305405602-ljksbgllkhgit5rfqehhvbpar7cn7lbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaProyectoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8jMEEzbXWsZ8WxofGxoo3VGoDiTApxTI',
    appId: '1:667305405602:ios:37c69aa5bca577f1c47bfb',
    messagingSenderId: '667305405602',
    projectId: 'eetaceaapp',
    storageBucket: 'eetaceaapp.appspot.com',
    iosClientId: '667305405602-luud18kbki4bgqhsfou9rh9orejkp4hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaProyectoFlutter.RunnerTests',
  );
}
